---
config:
  flowchart:
    curve: linear
---
graph TD;
	__start__([<p>__start__</p>]):::first
	context_provider(context_provider)
	discover_threat_model(discover_threat_model)
	discover_behavior(discover_behavior)
	discover_maintainability(discover_maintainability)
	council_coordinator(council_coordinator)
	evidence_agent(evidence_agent)
	council_judge(council_judge)
	summary(summary)
	__end__([<p>__end__</p>]):::last
	__start__ --> summary;
	context_provider --> discover_behavior;
	context_provider --> discover_maintainability;
	context_provider --> discover_threat_model;
	council_coordinator -.-> council_judge;
	council_coordinator -.-> evidence_agent;
	council_judge -. &nbsp;END&nbsp; .-> __end__;
	council_judge -.-> evidence_agent;
	discover_behavior --> council_coordinator;
	discover_maintainability --> council_coordinator;
	discover_threat_model --> council_coordinator;
	evidence_agent --> council_coordinator;
	summary --> context_provider;
	classDef default fill:#f2f0ff,line-height:1.2
	classDef first fill-opacity:0
	classDef last fill:#bfb6fc
