<project xmlns="http://maven.apache.org/POM/4.0.0">
  <modelVersion>4.0.0</modelVersion>
  <parent>
    <groupId>com.codeguard.benchmark</groupId>
    <artifactId>tradeflow-parent</artifactId>
    <version>1.0.0</version>
    <relativePath>../pom.xml</relativePath>
  </parent>
  <artifactId>tradeflow-boot</artifactId>
  <dependencies>
    <dependency>
      <groupId>com.codeguard.benchmark</groupId>
      <artifactId>tradeflow-web</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.codeguard.benchmark</groupId>
      <artifactId>tradeflow-persistence</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.codeguard.benchmark</groupId>
      <artifactId>tradeflow-integrations</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>com.codeguard.benchmark</groupId>
      <artifactId>tradeflow-worker</artifactId>
      <version>${project.version}</version>
    </dependency>
    <dependency>
      <groupId>org.springframework.boot</groupId>
      <artifactId>spring-boot-starter</artifactId>
    </dependency>
  </dependencies>
</project>
